[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HactarCE/hsearch"

[workspace.lints.rust]
rust_2018_idioms = "warn"
unused_crate_dependencies = "warn"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
doc_markdown = "warn"
manual_let_else = "warn"
semicolon_if_nothing_returned = "warn"
semicolon_inside_block = "warn"
stable_sort_primitive = "warn"
uninlined_format_args = "warn"

[workspace.dependencies]
bitbuffer = "0.11.3"
bnum = { version = "0.14.4", features = ["numtraits"] }
bumpalo = "3.20.2"
itertools = "0.14.0"
num-traits = "0.2.19"
rand = "0.10.1"
rapidhash = "4.5.1"
rayon = "1.12.0"
criterion = "0.8.2"
pretty_assertions = "1.4.1"
