[package]
name = "hsearch"
description = "Hactar's Hyperpuzzle Search Program"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HactarCE/hsearch"

[lints.rust]
rust_2018_idioms = "warn"
unused_crate_dependencies = "warn"

[lints.clippy]
correctness = { level = "deny", priority = -1 }
doc_markdown = "warn"
manual_let_else = "warn"
semicolon_if_nothing_returned = "warn"
semicolon_inside_block = "warn"
stable_sort_primitive = "warn"
uninlined_format_args = "warn"

[dependencies]
bitbuffer = "0.11.3"
itertools = "0.14.0"
rand = "0.10.1"
rayon = "1.12.0"
