//! Automated solver for 3×3×3×3 4-dimensional Rubik's cube.
//!
//! ## Puzzle description
//!
//! ### Facets
//!
//! The 3×3×3×3 puzzle exists in 4-dimensional Euclidean space. The 4 axes of
//! the space are [`X`], [`Y`], [`Z`], and [`W`].
//!
//! The puzzle has 8 [`Facet`]s, also called cells. Each assigned a letter.
//! Additionally, there are 4 slices between facets, which are also assigned
//! letters.
//!
//! | Axis  | Positive facet | Slice layer  | Negative facet |
//! | ----- | -------------- | ------------ | -------------- |
//! | [`X`] | [`R`]ight      | `M`iddle     | [`L`]eft       |
//! | [`Y`] | [`U`]p         | `E`quitorial | [`D`]own       |
//! | [`Z`] | [`F`]ront      | `S`tanding   | [`B`]ack       |
//! | [`W`] | [`O`]ut        | `P`lanetary  | [`I`]n         |
//!
//! ### Piece types
//!
//! Pieces are named based on their corresponding polytope element and on the
//! number of stickers/colors (`N`c where `N` is the number of colors).
//!
//! | Piece type | Element    | Stickers per piece | Piece count |
//! | ---------- | ---------- | ------------------ | ----------- |
//! | Core       |            | 0                  | 1           |
//! | Center     | facet/cell | 1                  | 8           |
//! | Ridge      | ridge/face | 2                  | 24          |
//! | Edge       | edge       | 3                  | 32          |
//! | Corner     | vertex     | 4                  | 16          |
//! | **Total**  |            |                    | **81**      |
//!
//! ### Twists
//!
//! Each twist is specified using 2-4 facet letters, sometimes followed by the
//! number `2`. The first letters indicate which facet the twist moves, and the
//! remaining letters indicate a perpendicular vector that is fixed by the
//! twist.
//!
//! For example, `IUR` indicates a twist of the [`I`] facet that fixes the
//! vector between [`U`] and [`R`]. In particular, it is the minimal clockwise
//! twist around the plane spanned by the normal vector of the [`I`] facet and
//! the average of the nomral vectors of the [`U`] and [`R`] facets.
//!
//! The number `2` following a turn indicates to perform the twist twice. For
//! example, `DF2` is equivalent to the sequence `DF DF`.
//!
//! ### State space
//!
//! #### Permutation
//!
//! The core and centers do not move. The remaining piece types are:
//!
//! | Piece type | Piece count |
//! | ---------- | ----------- |
//! | Ridge      | 24          |
//! | Edge       | 32          |
//! | Corner     | 16          |
//!
//! The following invariants apply:
//!
//! - The permutation parity of the corners is always even.
//! - The combined permutation parity of the ridges and edges is always even.
//!
//! This results in 24! × 32! × 16! ÷ 4 =
//! **853958999428346670146637167842740671369017657685146022707200000000000000**
//! permutation states. This is approximately 8.5396 × 10<sup>71</sup>.
//!
//! #### Orientation
//!
//! | Piece type | Piece count | Orientations | Distinguishable orientations |
//! | ---------- | ----------- | ------------ | ---------------------------- |
//! | Core       | 1           | 24           | 1                            |
//! | Center     | 6           | 8            | 1                            |
//! | Ridge      | 24          | 8            | 2                            |
//! | Edge       | 32          | 6            | 6                            |
//! | Corner     | 16          | 12           | 12                           |
//!
//! There are several invariants:
//!
//! - When all but one ridge is solved, the final unsolved ridge must be
//!   correctly oriented.
//! - When all but one corner is solved, the final unsolved corner cannot have
//!   its 3 stickers cycled (but they may have 2 pairs swapped).
//! - When all but one edge is solved, the final edge cannot have 2 of its
//!   stickers swapped (but it may have 3 of its stickers cycled).
//!
//! This results in 2<sup>23</sup> × 6<sup>31</sup> × 3 × 12<sup>15</sup> × 4 =
//! **2057209868254970923151671295243454844140433440768** orientation states.
//! This is approximately 2.05721 × 10<sup>48</sup>.
//!
//! #### Total
//!
//! Multiplying the permutation states by the orientation states yields
//! **1756772880709135843168526079081025059614484630149557651477156021733236798970168550600274887650082354207129600000000000000**
//! total puzzle states. This is approximately 1.75677 × 10<sup>120</sup>.
//!
//! Given any one of these states, the solver computes a sequence of moves that
//! takes it to the solved state.
//!
//! ## Domino reduction
//!
//! A core concept of the solver is generalized [**domino reduction**][dr].
//!
//! [dr]: https://www.speedsolving.com/wiki/index.php/Domino_Reduction
//!
//! In the context of 3^4, **domino symmetry** is the symmetry of a cube prism.
//! This project's convention is to place the cube in the YZW hyperplane; thus
//! domino symmetry is the symmetry group generated by cube rotations in YZW and
//! reflection along the X axis. It has 96 elements (48 rotations), as compared
//! to the 384 elements (192 rotations) of hypercube symmetry.
//!
//! The **domino 3^4** is the subpuzzle whose grip group is domino symmetry. (Of
//! course, we only consider rotational twists.) This subpuzzle has 88 twists:
//! 23 each on `R`/`L` (which have full cube symmetry) and 7 each on all the
//! other facets (which have square prism symmetry). Note that the domino 3^4
//! has one surprising invariant: there is a parity condition on edge
//! orientation between the `M` slice and the `R`/`L` layers, which divides the
//! state count by 2 from what a naive calculation would produce.
//!
//! A piece is **domino-oriented** if it is correctly oriented with respect to
//! the `R`/`L` axis; i.e., if it has an `R`/`L` sticker then that sticker is on
//! `R` or `L`, and if it does not have an `R`/`L` sticker then the piece
//! resides in `M`. Note that the `R`/`L` sticker may be on either `R` or `L`
//! regardless of color.
//!
//! **Domino reduction** is the process of reducing an unsolved 3^4 to an
//! unsolved domino 3^4. This consists of domino-orienting all pieces (i.e.,
//! placing all `R`/`L` stickers on the `R`/`L` facets) and resolving the edge
//! orientation parity condition.
//!
//! ## Domino projection
//!
//! The **domino projection** is a projection of the state space of 3^4 that can
//! be used to determine whether the puzzle has been successfully
//! domino-reduced. In the domino projection, each sticker is labelled based on
//! whether it belongs on `R`/`L` or on a different facet.
//!
//! - `R`/`L` ridge orientations are distinguishable.
//! - `M` ridge orientations are indistinguishable.
//! - Only 3 `R`/`L` edge orientations are distinguishable (as opposed to all
//!   6).
//! - `M` edge orientations are indistinguishable.
//! - Only 4 corner orientations are distinguishable (as opposed to all 12).
//!
//! Additionally, the projection includes the total modulo-2 orientation parity
//! for edges that belong in `M`. This is analogous to total [Reflecube] corner
//! mirror parity.
//!
//! [Reflecube]: https://www.nan.ma/reflecube/
//!
//! ## Stages
//!
//! At the time of writing, the solve stages are still being worked out.

#[cfg(test)]
extern crate criterion as _; // suppress unused-crate-dependencies warning

pub use fxhash::FxHashMap as HashMap;
pub use hsearch_core::*;

#[macro_use]
mod lut;
mod canonical;
mod prune;
mod search;
pub mod stages;
mod util;

pub use prelude::*;

/// Common imports.
pub mod prelude {
    pub use hsearch_core::*;

    pub use crate::Stage;
    pub use crate::canonical::PrevTwists;
    pub use crate::prune::*;
}

pub const SCRAMBLE_LEN: usize = 50;

pub use search::solve;
pub use stages::*;
pub use util::scramble;
