use std::{collections::HashSet, hash::Hash};

use crate::linalg::*;

/// [Point group](https://en.wikipedia.org/wiki/Point_group) generated by
/// matrices.
pub struct Group {
    generators: Vec<Mat4>,
}

impl Group {
    /// Constructs a group from generators.
    pub fn new(generators: Vec<Mat4>) -> Group {
        Group { generators }
    }

    /// Constructs the group of hypercube rotations.
    pub fn hypercube_rotations() -> Group {
        Group::new(vec![Mat4::rot(X, Y), Mat4::rot(X, Z), Mat4::rot(X, W)])
    }

    /// Returns all elements of the symmetry group.
    #[cfg(test)]
    pub fn elems(&self) -> Vec<Mat4> {
        self.orbit_with(vec![IDENT], |g, &m| g * m, |&m| m)
    }

    /// Returns the orbit of a set of initial points, given a function that
    /// serves as the group action and a function that returns a comparison key
    /// from a point.
    pub fn orbit_with<P, K: Eq + Hash>(
        &self,
        init: Vec<P>,
        act: impl Fn(Mat4, &P) -> P,
        get_key: impl Fn(&P) -> K,
    ) -> Vec<P> {
        let mut ret = init;
        let mut seen = HashSet::new();
        seen.extend(ret.iter().map(&get_key));
        let mut unprocessed_index = 0;
        while unprocessed_index < ret.len() {
            for &g in &self.generators {
                let new_elem = act(g, &ret[unprocessed_index]);
                if seen.insert(get_key(&new_elem)) {
                    ret.push(new_elem);
                }
            }
            unprocessed_index += 1;
        }
        ret
    }
}
